# Generated by Django 4.0.3 on 2022-04-19 00:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTable',
            fields=[
                ('album', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=200)),
                ('yob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtistTable',
            fields=[
                ('artist', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SongRater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SongTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('avg_rating', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songrater.songtable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songrater.user')),
            ],
        ),
    ]
